mixed-port: 7890
allow-lan: false
mode: Rule
log-level: debug
external-controller : 0.0.0.0:9090
external-ui : /root/clashui

proxy-providers:
  niuniu:
    type: http
    url: "è®¢é˜…é“¾æ¥"
    interval: 3600
    path: ./niuniu.yaml
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204

proxy-groups:

  - name: ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
    type: select
    use:
      - niuniu

  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - DIRECT
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸš€ æ‰‹åŠ¨åˆ‡æ¢

  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    use:
      - niuniu


rules:

 - GEOIP,CN,DIRECT
 - MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
